pipeline {
    agent any

    environment {
        IMAGE_NAME = "anjali8329/financeme-service"
    }

    stages {
        stage('Build') {
            steps {
                dir('financeme-service') {  // change directory if your code is nested
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t %IMAGE_NAME% financeme-service'
            }
        }

        stage('Docker Run') {
            steps {
                bat 'docker stop financeme-service || exit 0'
                bat 'docker rm financeme-service || exit 0'
                bat 'docker run -d -p 8081:8080 --name financeme-service %IMAGE_NAME%'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
