
pipeline {
  agent any

  environment {
    IMAGE_NAME = "anjali8329/financeme-service"
    IMAGE_TAG = "latest"
    PROJECT_DIR = "C:\\financeme-service\\financeme-service"
  }

  stages {
    stage('Build Maven Project') {
      steps {
        echo 'Running mvn clean package...'
        bat "cd %PROJECT_DIR% && mvn clean package -DskipTests"
      }
    }

    stage('Build Docker Image') {
      steps {
        echo 'Building Docker image...'
        bat "cd %PROJECT_DIR% && docker build -t %IMAGE_NAME%:%IMAGE_TAG% ."
      }
    }

    stage('Push Docker Image to Docker Hub') {
      steps {
        echo 'Pushing Docker image...'
        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          bat """
            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
            docker push %IMAGE_NAME%:%IMAGE_TAG%
          """
        }
      }
    }
  }

  post {
    success {
      echo 'Pipeline completed successfully!'
    }
    failure {
      echo 'Pipeline failed.'
    }
  }
}
